### PR TITLE
Add sponsorships

### PR DESCRIPTION
**Pull request by pkage**
this should be a PR just in case ive fucked it up and it makes the people with money angry

### CODE REVIEW

**Review by qaisjp — APPROVED** [review]

**Review by qaisjp — APPROVED** [review]
Looks fab 🙂

**Comment by elenalape** [comment]
They look quite squished

**Comment by elenalape** [comment]
Please can you make everything bigger (1.5 the current size or so), make Huel bigger, and also increase the padding, since everything looks quite squished?

**Comment by pkage** [comment]
increased sizes, increased margins.

screen shot 2019-02-22 at 11 11 20 am

**Comment by elenalape** [comment]
Please can you increase margins more, maybe 50px? And also currently there's no distinction in logo size between gold and silver :/

**Pull request merged**
