### PR TITLE
Add MLH banner

### LINKED ISSUE #8: Add MLH banner
see https://mlh.io/brand-guidelines

### PR DESCRIPTION
**Pull request by ViRb3**
Fix #8

### CODE REVIEW

**Review by qaisjp — CHANGES_REQUESTED** [review]
Invalid html. `div` should not be inside `head`.

**Comment by qaisjp** [comment]
ping (?)

**Comment by ViRb3** [comment]
Check if update is good please

**Review by qaisjp — APPROVED** [review]
lgtm thanks.

**Pull request merged**
